name: Notify Slack

on:
  schedule:
    - cron: '0 13 * * *'

jobs:
  send-notification:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python notify_weight.py
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        PIXELA_USER_NAME: ${{ secrets.PIXELA_USER_NAME }}
        PIXELA_USER_TOKEN: ${{ secrets.PIXELA_USER_TOKEN }}

    - name: Enable workflow
      run: |
        curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/enable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

